# This Program calculates the price of a meal based on the number of people eating
# I have added drinks to go along with the meal and take-home icecream for the kids

num1 = float(input("What is the price of a child's meal?: "))
num2 = float(input("What is the price of an adult's meal?: "))
number_of_children = int(input("How many children are there?: "))
Number_of_adult = int(input("How many adult are there?: "))
total_child_meal = (num1 * number_of_children)
total_adult_meal = (num2 * Number_of_adult)
drinks = float(input('What is the price of a drink? '))
number_of_drinks = int(input('How many drinks are there? '))
total_drinks = (drinks * number_of_drinks)
take_home_icecream = float(input('What is the price of icecream? '))
number_of_icecream = int(input('How many icecream are there? '))
total_icecream = (take_home_icecream * number_of_icecream)
sub_total = float((total_adult_meal + total_child_meal + total_drinks + total_icecream))
print()
print(f'Subtotal: ${sub_total:.2f}')
print()
tax = float(input('What is the sales tax rate? '))
sales_tax = float(sub_total * tax/100)
print(f'Sales Tax: ${sales_tax:.2f}')
total = (sales_tax + sub_total)
print(f'Total: ${total:.2f}')
print()
payment = float(input('What is the payment amount? '))
change = float(payment - total)
print(f'Change: ${change:.2f}')